require('dotenv').config();
const express = require('express');
const cors = require('cors');
const authRoutes = require('./routes/authRoutes');
const usuarioRoutes =require('./routes/usuarioRoutes');
const productoRoutes =require('./routes/productoRoutes');
const mesaRoutes =require('./routes/mesaRoutes');
const ordenRoutes =require('./routes/ordenRoutes');
const cocinaRoutes = require('./routes/cocinaRoutes');
const reporteRoutes = require('./routes/reporteRoutes');
const dashboardRoutes =require("./routes/dashboardRoutes");
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/auth', authRoutes);
app.use('/api/usuarios',usuarioRoutes);
app.use('/api/productos',productoRoutes);
app.use('/api/mesas',mesaRoutes);
app.use('/api/ordenes',ordenRoutes);
app.use('/api/cocina', cocinaRoutes);
app.use("/api/dashboard",dashboardRoutes);
app.use('/api/reportes', reporteRoutes);
app.listen(4000, () => {
    console.log('Servidor corriendo en puerto 4000');
}); 